TWILIO_ACCOUNT_SID = ENV['TWILIO_ACCOUNT_SID'] || false
TWILIO_AUTH_TOKEN = ENV['TWILIO_AUTH_TOKEN'] || false
TWILIO_APP_SID = ENV['TWILIO_APP_SID'] || false

FACEBOOK_APP_ID = ENV['FACEBOOK_APP_ID'] || ''
FACEBOOK_APP_SECRET = ENV['FACEBOOK_APP_SECRET'] || ''
